runtime: python310

handlers:
- url: .*
  script: main.app


env_variables:
  BOT_NAME: 'pspricesbot'
  BOT_TOKEN: "503b1bf29967e529-d68be19082848336-8893c5fb70668580"
  DATA_KEYF_NAME: 'service-account.json'
  DATA_SHEET: 'metals_prices'
  GOOGLE_APPLICATION_CREDENTIALS: './secrets/service-account.json'
  SPREADSHEET_DATA: '1qqJCFxxGV4sjm8cKKuWSaQFjCCZt3x8idm28RcVgnR4'
  SPREADSHEET_USERS: '1McMyMHCuL9ujSNGE2UBnoaYV5Yw-KwLhBQhBhYvNUi0'
  URL_ONE: 'https://www.lme.com/Metals/Non-ferrous/LME-Copper#Trading+day+summary'
  URL_THREE: 'https://www.westmetall.com/en/markdaten/php?action\=table&field\=LME_Cu_cash'
  URL_TWO: 'https://www.lbma.org.uk/prices-and-data/precious-metal-prices#/table'
  GATHER_JOB: 'gatherMetalsData'
