apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pricestracker


spec:
  template:
    spec:
      containers:
        env:
        - name: FIREBASE_URL
          value: 'https://prices-tracker-cr-default-rtdb.europe-west1.firebasedatabase.app/'
        - name: SPREADSHEET_DATA
          value: 1qqJCFxxGV4sjm8cKKuWSaQFjCCZt3x8idm28RcVgnR4
        - name: SPREADSHEET_USERS
          value: 1McMyMHCuL9ujSNGE2UBnoaYV5Yw-KwLhBQhBhYvNUi0
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ./secrets/service-account2.json